#include "triangle.hpp"

// Generated from the supplied C1 Scratch kernel by tools/extract_triangle.py.
namespace scratch::triangle {
void draw_fixed(int ax,int ay,int bx,int by,int cx,int cy,unsigned rgb,int units_per_pixel) {
    if(units_per_pixel<=0)return;
    asm volatile(
        "pen_penUp;"
        "pen_setPenColorToColor COLOR=%6;"
        "data_setvariableto VALUE=(operator_mathop NUM=(operator_add NUM1=(operator_multiply NUM1=(operator_subtract NUM1=(operator_divide NUM1=%2 NUM2=%7) NUM2=(operator_divide NUM1=%4 NUM2=%7)) NUM2=(operator_subtract NUM1=(operator_divide NUM1=%2 NUM2=%7) NUM2=(operator_divide NUM1=%4 NUM2=%7))) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(operator_divide NUM1=%3 NUM2=%7) NUM2=(operator_divide NUM1=%5 NUM2=%7)) NUM2=(operator_subtract NUM1=(operator_divide NUM1=%3 NUM2=%7) NUM2=(operator_divide NUM1=%5 NUM2=%7)))) OPERATOR=\"sqrt\") VARIABLE=\"__scl_triangle_a\";"
        "data_setvariableto VALUE=(operator_mathop NUM=(operator_add NUM1=(operator_multiply NUM1=(operator_subtract NUM1=(operator_divide NUM1=%0 NUM2=%7) NUM2=(operator_divide NUM1=%4 NUM2=%7)) NUM2=(operator_subtract NUM1=(operator_divide NUM1=%0 NUM2=%7) NUM2=(operator_divide NUM1=%4 NUM2=%7))) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(operator_divide NUM1=%1 NUM2=%7) NUM2=(operator_divide NUM1=%5 NUM2=%7)) NUM2=(operator_subtract NUM1=(operator_divide NUM1=%1 NUM2=%7) NUM2=(operator_divide NUM1=%5 NUM2=%7)))) OPERATOR=\"sqrt\") VARIABLE=\"__scl_triangle_b\";"
        "data_setvariableto VALUE=(operator_mathop NUM=(operator_add NUM1=(operator_multiply NUM1=(operator_subtract NUM1=(operator_divide NUM1=%0 NUM2=%7) NUM2=(operator_divide NUM1=%2 NUM2=%7)) NUM2=(operator_subtract NUM1=(operator_divide NUM1=%0 NUM2=%7) NUM2=(operator_divide NUM1=%2 NUM2=%7))) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(operator_divide NUM1=%1 NUM2=%7) NUM2=(operator_divide NUM1=%3 NUM2=%7)) NUM2=(operator_subtract NUM1=(operator_divide NUM1=%1 NUM2=%7) NUM2=(operator_divide NUM1=%3 NUM2=%7)))) OPERATOR=\"sqrt\") VARIABLE=\"__scl_triangle_c\";"
        "data_setvariableto VALUE=(operator_add NUM1=(data_variable VARIABLE=\"__scl_triangle_a\") NUM2=(operator_add NUM1=(data_variable VARIABLE=\"__scl_triangle_b\") NUM2=(data_variable VARIABLE=\"__scl_triangle_c\"))) VARIABLE=\"__scl_triangle_semiperimeter\";"
        "data_setvariableto VALUE=(operator_divide NUM1=(operator_add NUM1=(operator_multiply NUM1=(operator_divide NUM1=%0 NUM2=%7) NUM2=(data_variable VARIABLE=\"__scl_triangle_a\")) NUM2=(operator_add NUM1=(operator_multiply NUM1=(operator_divide NUM1=%2 NUM2=%7) NUM2=(data_variable VARIABLE=\"__scl_triangle_b\")) NUM2=(operator_multiply NUM1=(operator_divide NUM1=%4 NUM2=%7) NUM2=(data_variable VARIABLE=\"__scl_triangle_c\")))) NUM2=(data_variable VARIABLE=\"__scl_triangle_semiperimeter\")) VARIABLE=\"__scl_triangle_ix\";"
        "data_setvariableto VALUE=(operator_divide NUM1=(operator_add NUM1=(operator_multiply NUM1=(operator_divide NUM1=%1 NUM2=%7) NUM2=(data_variable VARIABLE=\"__scl_triangle_a\")) NUM2=(operator_add NUM1=(operator_multiply NUM1=(operator_divide NUM1=%3 NUM2=%7) NUM2=(data_variable VARIABLE=\"__scl_triangle_b\")) NUM2=(operator_multiply NUM1=(operator_divide NUM1=%5 NUM2=%7) NUM2=(data_variable VARIABLE=\"__scl_triangle_c\")))) NUM2=(data_variable VARIABLE=\"__scl_triangle_semiperimeter\")) VARIABLE=\"__scl_triangle_iy\";"
        "data_setvariableto VALUE=(operator_divide NUM1=(data_variable VARIABLE=\"__scl_triangle_semiperimeter\") NUM2=\"2\") VARIABLE=\"__scl_triangle_semiperimeter\";"
        "data_setvariableto VALUE=(operator_mathop NUM=(operator_multiply NUM1=(operator_multiply NUM1=(data_variable VARIABLE=\"__scl_triangle_semiperimeter\") NUM2=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_semiperimeter\") NUM2=(data_variable VARIABLE=\"__scl_triangle_a\"))) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_semiperimeter\") NUM2=(data_variable VARIABLE=\"__scl_triangle_b\")) NUM2=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_semiperimeter\") NUM2=(data_variable VARIABLE=\"__scl_triangle_c\")))) OPERATOR=\"sqrt\") VARIABLE=\"__scl_triangle_area\";"
        "data_setvariableto VALUE=(operator_mathop NUM=(data_variable VARIABLE=\"__scl_triangle_area\") OPERATOR=\"abs\") VARIABLE=\"__scl_triangle_area\";"
        "data_setvariableto VALUE=(operator_divide NUM1=(operator_multiply NUM1=\"2\" NUM2=(data_variable VARIABLE=\"__scl_triangle_area\")) NUM2=(data_variable VARIABLE=\"__scl_triangle_semiperimeter\")) VARIABLE=\"__scl_triangle_diameter\";"
        "data_setvariableto VALUE=\"1\" VARIABLE=\"__scl_triangle_scale\";"
        "control_if CONDITION=(operator_and OPERAND1=(operator_gt OPERAND1=(data_variable VARIABLE=\"__scl_triangle_area\") OPERAND2=0) OPERAND2=(operator_gt OPERAND1=(data_variable VARIABLE=\"__scl_triangle_diameter\") OPERAND2=0)) SUBSTACK %{ control_repeat TIMES=\"8\" SUBSTACK=%{ data_setvariableto VALUE=(operator_divide NUM1=(data_variable VARIABLE=\"__scl_triangle_scale\") NUM2=\"2\") VARIABLE=\"__scl_triangle_scale\"; pen_setPenSizeTo SIZE=(operator_multiply NUM1=(data_variable VARIABLE=\"__scl_triangle_diameter\") NUM2=(data_variable VARIABLE=\"__scl_triangle_scale\")); motion_gotoxy X=(operator_add NUM1=(operator_divide NUM1=%0 NUM2=%7) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_ix\") NUM2=(operator_divide NUM1=%0 NUM2=%7)) NUM2=(data_variable VARIABLE=\"__scl_triangle_scale\"))) Y=(operator_add NUM1=(operator_divide NUM1=%1 NUM2=%7) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_iy\") NUM2=(operator_divide NUM1=%1 NUM2=%7)) NUM2=(data_variable VARIABLE=\"__scl_triangle_scale\"))); pen_penDown; motion_gotoxy X=(operator_add NUM1=(operator_divide NUM1=%2 NUM2=%7) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_ix\") NUM2=(operator_divide NUM1=%2 NUM2=%7)) NUM2=(data_variable VARIABLE=\"__scl_triangle_scale\"))) Y=(operator_add NUM1=(operator_divide NUM1=%3 NUM2=%7) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_iy\") NUM2=(operator_divide NUM1=%3 NUM2=%7)) NUM2=(data_variable VARIABLE=\"__scl_triangle_scale\"))); motion_gotoxy X=(operator_add NUM1=(operator_divide NUM1=%4 NUM2=%7) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_ix\") NUM2=(operator_divide NUM1=%4 NUM2=%7)) NUM2=(data_variable VARIABLE=\"__scl_triangle_scale\"))) Y=(operator_add NUM1=(operator_divide NUM1=%5 NUM2=%7) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_iy\") NUM2=(operator_divide NUM1=%5 NUM2=%7)) NUM2=(data_variable VARIABLE=\"__scl_triangle_scale\"))); motion_gotoxy X=(operator_add NUM1=(operator_divide NUM1=%0 NUM2=%7) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_ix\") NUM2=(operator_divide NUM1=%0 NUM2=%7)) NUM2=(data_variable VARIABLE=\"__scl_triangle_scale\"))) Y=(operator_add NUM1=(operator_divide NUM1=%1 NUM2=%7) NUM2=(operator_multiply NUM1=(operator_subtract NUM1=(data_variable VARIABLE=\"__scl_triangle_iy\") NUM2=(operator_divide NUM1=%1 NUM2=%7)) NUM2=(data_variable VARIABLE=\"__scl_triangle_scale\"))); pen_penUp; %}; %};"
        "pen_penUp;"
        : : "r"(ax), "r"(ay), "r"(bx), "r"(by), "r"(cx), "r"(cy), "r"(rgb), "r"(units_per_pixel) : "memory");
}
void draw(int ax,int ay,int bx,int by,int cx,int cy,unsigned rgb) { draw_fixed(ax,ay,bx,by,cx,cy,rgb,1); }
}
