# Included before project(): select the GNU-style Clang driver, not MSVC.
set(SCRATCH_TOOLCHAIN_ROOT "$ENV{SCRATCH_TOOLCHAIN_ROOT}" CACHE PATH "Clang, standard-library and linker prefix")
set(LLVM_ROOT "$ENV{LLVM_ROOT}" CACHE PATH "LLVM C API prefix (may differ from the host compiler prefix)")
set(_scratch_compiler_hints)
if(SCRATCH_TOOLCHAIN_ROOT)
  list(APPEND _scratch_compiler_hints "${SCRATCH_TOOLCHAIN_ROOT}/bin")
endif()
if(LLVM_ROOT)
  list(APPEND _scratch_compiler_hints "${LLVM_ROOT}/bin")
endif()
if(NOT DEFINED CMAKE_C_COMPILER AND "$ENV{CC}" STREQUAL "")
  find_program(_scratch_clang NAMES clang-22 clang HINTS ${_scratch_compiler_hints} REQUIRED)
  set(CMAKE_C_COMPILER "${_scratch_clang}" CACHE FILEPATH "Clang C compiler")
endif()
if(NOT DEFINED CMAKE_CXX_COMPILER AND "$ENV{CXX}" STREQUAL "")
  find_program(_scratch_clangxx NAMES clang++-22 clang++ HINTS ${_scratch_compiler_hints} REQUIRED)
  set(CMAKE_CXX_COMPILER "${_scratch_clangxx}" CACHE FILEPATH "Clang C++ compiler")
endif()
