if(NOT CMAKE_CXX_COMPILER_ID MATCHES "^(Clang|AppleClang)$")
  message(FATAL_ERROR "scratch-llvm requires Clang. Configure a new build directory with clang/clang++, preferably using the clang preset.")
endif()
if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
  message(FATAL_ERROR "Use the GNU-style Clang driver and an independent runtime/sysroot. On Windows use the prepared LLVM/MinGW toolchain, not clang-cl or a Visual Studio generator.")
endif()

set(SCRATCH_STDLIB "libc++" CACHE STRING "Host C++ standard library: libc++ or libstdc++")
set_property(CACHE SCRATCH_STDLIB PROPERTY STRINGS "libc++" "libstdc++")
set(SCRATCH_STDLIB_ROOT "$ENV{SCRATCH_STDLIB_ROOT}" CACHE PATH "Optional separately prepared standard-library prefix")
set(SCRATCH_LINKER "lld" CACHE STRING "Clang linker name, absolute linker path, or default")
add_library(scratch-host INTERFACE)
target_compile_features(scratch-host INTERFACE cxx_std_17)
target_compile_options(scratch-host INTERFACE "$<$<COMPILE_LANGUAGE:CXX>:-Wall;-Wextra;-Wpedantic>")
if(NOT SCRATCH_STDLIB STREQUAL "libc++" AND NOT SCRATCH_STDLIB STREQUAL "libstdc++")
  message(FATAL_ERROR "SCRATCH_STDLIB must be libc++ or libstdc++")
endif()
if(WIN32 AND NOT MINGW)
  message(FATAL_ERROR "The Windows host needs a MinGW/UCRT sysroot. Merely choosing clang.exe with an MSVC default target still requires the Visual Studio SDK.")
endif()
if(NOT SCRATCH_STDLIB_ROOT OR NOT SCRATCH_STDLIB STREQUAL "libc++")
  target_compile_options(scratch-host INTERFACE "$<$<COMPILE_LANGUAGE:CXX>:-stdlib=${SCRATCH_STDLIB}>")
endif()
target_link_options(scratch-host INTERFACE "-stdlib=${SCRATCH_STDLIB}")
set(_scratch_probe_flags "-stdlib=${SCRATCH_STDLIB}")
set(_scratch_probe_libraries)
set(SCRATCH_HOST_RUNTIME_DIRS)
if(SCRATCH_STDLIB_ROOT)
  if(SCRATCH_STDLIB STREQUAL "libc++")
    find_path(SCRATCH_LIBCXX_INCLUDE_DIR __config
      HINTS "${SCRATCH_STDLIB_ROOT}/include/c++/v1" NO_DEFAULT_PATH REQUIRED)
    target_compile_options(scratch-host INTERFACE "$<$<COMPILE_LANGUAGE:CXX>:-nostdinc++>")
    # CMake otherwise strips an explicit directory it detected as implicit,
    # even though -nostdinc++ has disabled that implicit directory.
    target_compile_options(scratch-host INTERFACE "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-isystem \"${SCRATCH_LIBCXX_INCLUDE_DIR}\">")
    string(APPEND _scratch_probe_flags " -nostdinc++ -isystem \"${SCRATCH_LIBCXX_INCLUDE_DIR}\"")
  endif()
  set(_scratch_stdlib_dirs "${SCRATCH_STDLIB_ROOT}/lib/c++" "${SCRATCH_STDLIB_ROOT}/lib/unwind" "${SCRATCH_STDLIB_ROOT}/lib" "${SCRATCH_STDLIB_ROOT}/lib/${CMAKE_LIBRARY_ARCHITECTURE}")
  target_link_directories(scratch-host INTERFACE ${_scratch_stdlib_dirs})
  foreach(_directory IN LISTS _scratch_stdlib_dirs)
    string(APPEND _scratch_probe_flags " -L\"${_directory}\"")
    if(EXISTS "${_directory}")
      list(APPEND SCRATCH_HOST_RUNTIME_DIRS "${_directory}")
    endif()
  endforeach()
endif()
if(SCRATCH_STDLIB STREQUAL "libc++" AND UNIX AND NOT APPLE)
  find_library(SCRATCH_LIBCXXABI_LIBRARY NAMES c++abi
    HINTS ${_scratch_stdlib_dirs} "${LLVM_ROOT}/lib" REQUIRED)
  target_link_libraries(scratch-host INTERFACE "${SCRATCH_LIBCXXABI_LIBRARY}")
  list(APPEND _scratch_probe_libraries "${SCRATCH_LIBCXXABI_LIBRARY}")
endif()
if(NOT SCRATCH_LINKER STREQUAL "default")
  if(IS_ABSOLUTE "${SCRATCH_LINKER}")
    if(NOT EXISTS "${SCRATCH_LINKER}")
      message(FATAL_ERROR "Configured linker does not exist: ${SCRATCH_LINKER}")
    endif()
    set(_scratch_link_flag "--ld-path=${SCRATCH_LINKER}")
  else()
    set(_scratch_link_flag "-fuse-ld=${SCRATCH_LINKER}")
  endif()
  target_link_options(scratch-host INTERFACE "${_scratch_link_flag}")
  string(APPEND _scratch_probe_flags " \"${_scratch_link_flag}\"")
endif()

include(CheckCXXSourceCompiles)
set(CMAKE_REQUIRED_FLAGS "${_scratch_probe_flags}")
set(CMAKE_REQUIRED_LIBRARIES ${_scratch_probe_libraries})
unset(SCRATCH_HOST_TOOLCHAIN_WORKS CACHE)
check_cxx_source_compiles("#include <filesystem>\n#include <stdexcept>\n#include <string>\nint main() { try { std::filesystem::path p(\"toolchain\"); throw std::runtime_error(p.string()); } catch (const std::exception&) { return 0; } }" SCRATCH_HOST_TOOLCHAIN_WORKS)
unset(CMAKE_REQUIRED_FLAGS)
unset(CMAKE_REQUIRED_LIBRARIES)
if(NOT SCRATCH_HOST_TOOLCHAIN_WORKS)
  message(FATAL_ERROR "Clang could not link C++17 filesystem/exceptions with ${SCRATCH_STDLIB} and ${SCRATCH_LINKER}. Prepare the standard library, ABI library, linker and platform sysroot; see docs/BUILDING.md.")
endif()
message(STATUS "Host toolchain: ${CMAKE_CXX_COMPILER}; standard library=${SCRATCH_STDLIB}; linker=${SCRATCH_LINKER}")
