set(LLVM_CONFIG_EXECUTABLE "" CACHE FILEPATH "Optional llvm-config 22 executable")
if(NOT LLVM_CONFIG_EXECUTABLE)
  find_program(_scratch_llvm_config NAMES llvm-config-22 llvm-config HINTS "${LLVM_ROOT}/bin")
  if(_scratch_llvm_config)
    set(LLVM_CONFIG_EXECUTABLE "${_scratch_llvm_config}" CACHE FILEPATH "Optional llvm-config 22 executable" FORCE)
  endif()
endif()
set(_llvm_lib_hints "${LLVM_ROOT}/lib" "${LLVM_ROOT}/lib64")
if(LLVM_CONFIG_EXECUTABLE AND NOT CMAKE_CROSSCOMPILING)
  execute_process(COMMAND "${LLVM_CONFIG_EXECUTABLE}" --version OUTPUT_VARIABLE _llvm_version OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _llvm_config_status)
  if(_llvm_config_status EQUAL 0)
    if(NOT _llvm_version MATCHES "^22\.")
      message(FATAL_ERROR "LLVM C API 22.x is required; llvm-config reports ${_llvm_version}")
    endif()
    execute_process(COMMAND "${LLVM_CONFIG_EXECUTABLE}" --libdir OUTPUT_VARIABLE _llvm_libdir OUTPUT_STRIP_TRAILING_WHITESPACE)
    list(PREPEND _llvm_lib_hints "${_llvm_libdir}")
  endif()
endif()
find_library(LLVM_C_LIBRARY NAMES LLVM-C LLVM-22 LLVM LLVM-22.1
  HINTS ${_llvm_lib_hints} NO_DEFAULT_PATH)
if(NOT LLVM_C_LIBRARY)
  find_library(LLVM_C_LIBRARY NAMES LLVM-C LLVM-22 LLVM LLVM-22.1)
endif()
if(NOT LLVM_C_LIBRARY AND UNIX)
  find_file(LLVM_C_LIBRARY NAMES libLLVM.so.22.1 libLLVM-22.so.1 libLLVM.so.22
    HINTS ${_llvm_lib_hints} "/usr/lib/${CMAKE_LIBRARY_ARCHITECTURE}" /usr/lib /usr/local/lib)
endif()
if(NOT LLVM_C_LIBRARY)
  message(FATAL_ERROR "LLVM C API link library not found. Set LLVM_ROOT or LLVM_C_LIBRARY; prepare LLVM 22 libraries separately from Clang.")
endif()
if(NOT EXISTS "${LLVM_C_LIBRARY}")
  message(FATAL_ERROR "Configured LLVM C API link library does not exist: ${LLVM_C_LIBRARY}")
endif()
find_path(LLVM_C_INCLUDE_DIR llvm-c/Core.h
  HINTS "${PROJECT_SOURCE_DIR}/third_party/llvm/include" "${LLVM_ROOT}/include" REQUIRED)
set(LLVM_C_RUNTIME "$ENV{SCRATCH_LLVM_LIBRARY}" CACHE FILEPATH "LLVM C API shared library (DLL, .so or .dylib), used by runtime tooling")
if(NOT LLVM_C_RUNTIME)
  if(WIN32)
    find_file(_llvm_runtime NAMES libLLVM-22.dll LLVM-C.dll LLVM.dll
      HINTS "${LLVM_ROOT}/bin" "${SCRATCH_TOOLCHAIN_ROOT}/bin" "${_llvm_libdir}/../bin")
  elseif(LLVM_C_LIBRARY MATCHES "\\.(so(\\.[0-9.]+)?|dylib)$")
    set(_llvm_runtime "${LLVM_C_LIBRARY}")
  else()
    find_file(_llvm_runtime NAMES libLLVM.so.22.1 libLLVM-22.so.1 libLLVM-22.so libLLVM.dylib
      HINTS ${_llvm_lib_hints})
  endif()
  if(_llvm_runtime)
    set(LLVM_C_RUNTIME "${_llvm_runtime}" CACHE FILEPATH "LLVM C API shared library" FORCE)
  endif()
endif()
if(NOT LLVM_C_RUNTIME OR NOT EXISTS "${LLVM_C_RUNTIME}")
  message(FATAL_ERROR "Set LLVM_C_RUNTIME to the actual LLVM 22 shared library; an import/static library cannot be loaded by Python.")
endif()
add_library(scratch-llvm-c INTERFACE)
target_include_directories(scratch-llvm-c SYSTEM INTERFACE "${LLVM_C_INCLUDE_DIR}")
target_link_libraries(scratch-llvm-c INTERFACE "${LLVM_C_LIBRARY}")
get_filename_component(_llvm_runtime_dir "${LLVM_C_RUNTIME}" DIRECTORY)
list(APPEND SCRATCH_HOST_RUNTIME_DIRS "${_llvm_runtime_dir}")
if(NOT WIN32)
  list(REMOVE_DUPLICATES SCRATCH_HOST_RUNTIME_DIRS)
  set(CMAKE_BUILD_RPATH "${SCRATCH_HOST_RUNTIME_DIRS}")
endif()
message(STATUS "LLVM C API link library: ${LLVM_C_LIBRARY}")
message(STATUS "LLVM C API runtime: ${LLVM_C_RUNTIME}")
